refactor: copy log file at later point in time

diff --git a/suse/TEST-30-ISCSI-adapt-for-openQA.patch b/suse/TEST-30-ISCSI-adapt-for-openQA.patch
--- a/suse/TEST-30-ISCSI-adapt-for-openQA.patch
+++ b/suse/TEST-30-ISCSI-adapt-for-openQA.patch
@@ -1,14 +1,14 @@
-From 7fb4ec73d3d445f338c0a6fab9329e1b9281934f Mon Sep 17 00:00:00 2001
+From 740ccf4f039b95787931cb932d9f79746997ad2a Mon Sep 17 00:00:00 2001
 From: Robert Richardson <robert.richardson@suse.com>
 Date: Wed, 13 Apr 2022 12:02:05 +0200
 Subject: [PATCH] test 30 patch
 
 ---
- test/TEST-30-ISCSI/test.sh | 14 +++++++++-----
- 1 file changed, 9 insertions(+), 5 deletions(-)
+ test/TEST-30-ISCSI/test.sh | 13 ++++++++-----
+ 1 file changed, 8 insertions(+), 5 deletions(-)
 
 diff --git a/test/TEST-30-ISCSI/test.sh b/test/TEST-30-ISCSI/test.sh
-index 5f0063f8..830a99c7 100755
+index 5f0063f8..524f9470 100755
 --- a/test/TEST-30-ISCSI/test.sh
 +++ b/test/TEST-30-ISCSI/test.sh
 @@ -13,6 +13,8 @@ TEST_DESCRIPTION="root filesystem over iSCSI with $USE_NETWORK"
@@ -20,16 +20,15 @@ index 5f0063f8..830a99c7 100755
  DEBUGFAIL="loglevel=1"
  #DEBUGFAIL="rd.shell rd.break rd.debug loglevel=7 "
  DEBUGFAIL="rd.debug loglevel=7 "
-@@ -44,6 +46,8 @@ run_server() {
-     # Cleanup the terminal if we have one
-     tty -s && stty sane
- 
-+    cp $TESTDIR/server.log /tmp/dracut-testsuite-logs/$test_name-test_run_server.log
-+
-     if ! [[ $SERIAL ]]; then
-         while :; do
-             grep Serving "$TESTDIR"/server.log && break
-@@ -188,7 +192,7 @@ test_setup() {
+@@ -122,6 +124,7 @@ do_test_run() {
+ test_run() {
+     if ! run_server; then
+         echo "Failed to start server" 1>&2
++        cp $TESTDIR/server.log /tmp/dracut-testsuite-logs/$test_name-test_run_server.log
+         return 1
+     fi
+     do_test_run
+@@ -188,7 +191,7 @@ test_setup() {
      # We do it this way so that we do not risk trashing the host mdraid
      # devices, volume groups, encrypted partitions, etc.
      "$basedir"/dracut.sh -l -i "$TESTDIR"/overlay / \
@@ -38,7 +37,7 @@ index 5f0063f8..830a99c7 100755
          -d "piix ide-gd_mod ata_piix ext3 sd_mod" \
          --no-hostonly-cmdline -N \
          -f "$TESTDIR"/initramfs.makeroot "$KVERSION" || return 1
-@@ -279,7 +283,7 @@ test_setup() {
+@@ -279,7 +282,7 @@ test_setup() {
      # We do it this way so that we do not risk trashing the host mdraid
      # devices, volume groups, encrypted partitions, etc.
      "$basedir"/dracut.sh -l -i "$TESTDIR"/overlay / \
@@ -47,7 +46,7 @@ index 5f0063f8..830a99c7 100755
          -d "piix ide-gd_mod ata_piix ext3 sd_mod" \
          --nomdadmconf \
          --no-hostonly-cmdline -N \
-@@ -316,7 +320,7 @@ test_setup() {
+@@ -316,7 +319,7 @@ test_setup() {
      )
      # Make client's dracut image
      "$basedir"/dracut.sh -l -i "$TESTDIR"/overlay / \
@@ -56,7 +55,7 @@ index 5f0063f8..830a99c7 100755
          -a "debug ${USE_NETWORK}" \
          --no-hostonly-cmdline -N \
          -f "$TESTDIR"/initramfs.testing "$KVERSION" || return 1
-@@ -332,7 +336,7 @@ test_setup() {
+@@ -332,7 +335,7 @@ test_setup() {
      )
      # Make server's dracut image
      "$basedir"/dracut.sh -l -i "$TESTDIR"/overlay / \
@@ -65,7 +64,7 @@ index 5f0063f8..830a99c7 100755
          -d "af_packet piix ide-gd_mod ata_piix ext3 sd_mod e1000 drbg" \
          --no-hostonly-cmdline -N \
          -f "$TESTDIR"/initramfs.server "$KVERSION" || return 1
-@@ -348,4 +352,4 @@ test_cleanup() {
+@@ -348,4 +351,4 @@ test_cleanup() {
  }
  
  # shellcheck disable=SC1090
